/*  apc-modbus-hid.h - data to monitor APC USB/HID devices with NUT
*
*  Copyright (C)
*      2017            Dmitry Togushev <jtprofacc@gmain.com>
*
*      Based on apc-hid.h NUT (http://networkupstools.org/)
*
*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*
*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*
*/

/*
*	Implements HID over USB and MODBUS over USB protocols for Schneider Electric SMT and SRT family models.
*	Check
*	APPLICATION NOTE #178 (http://www.apc.com/salestools/MPAO-99NQF6/MPAO-99NQF6_R1_EN.pdf)
*	APPLICATION NOTE #176 (http://www.apc.com/salestools/MPAO-98KJ7F/MPAO-98KJ7F_R1_EN.pdf)
*	for more information
*/

#ifndef APC_SMT_MB_H
#define APC_SMT_MB_H

#include "usbhid-ups.h"
#include "modbustypes.h"
#include "usb-common.h"

// Code is generated automatically upon 'Modbus Implementation in APC Smart-UPS' (http://www.apc.com/salestools/MPAO-98KJ7F/MPAO-98KJ7F_R1_EN.pdf)

#define BF_UPSSTATUS_STATEONLINE 0x0002
#define BF_UPSSTATUS_STATEONBATTERY 0x0004
#define BF_UPSSTATUS_STATEOUTPUTOFF 0x0010
#define BF_UPSSTATUS_FAULT 0x0020
#define BF_UPSSTATUS_INPUTBAD 0x0040
#define BF_UPSSTATUS_TEST 0x0080
#define BF_UPSSTATUS_PENDINGOUTPUTON 0x0100
#define BF_UPSSTATUS_PENDINGOUTPUTOFF 0x0200
#define BF_UPSSTATUS_HIGHEFFICIENCY 0x2000
#define BF_UPSSTATUS_INFORMATIONALALERT 0x4000
#define BF_SIMPLESIGNALINGSTATUS_POWERFAILURE 0x0001
#define BF_SIMPLESIGNALINGSTATUS_SHUTDOWNIMMINENT 0x0002
#define BF_GENERALERROR_SITEWIRING 0x0001
#define BF_GENERALERROR_EEPROM 0x0002
#define BF_GENERALERROR_ADCONVERTER 0x0004
#define BF_GENERALERROR_LOGICPOWERSUPPLY 0x0008
#define BF_GENERALERROR_INTERNALCOMMUNICATION 0x0010
#define BF_GENERALERROR_UIBUTTON 0x0020
#define BF_GENERALERROR_EPOACTIVE 0x0080
#define BF_POWERSYSTEMERROR_OUTPUTOVERLOAD 0x0001
#define BF_POWERSYSTEMERROR_OUTPUTSHORTCIRCUIT 0x0002
#define BF_POWERSYSTEMERROR_OUTPUTOVERVOLTAGE 0x0004
#define BF_POWERSYSTEMERROR_OVERTEMPERATURE 0x0010
#define BF_POWERSYSTEMERROR_BACKFEEDRELAY 0x0020
#define BF_POWERSYSTEMERROR_AVRRELAY 0x0040
#define BF_POWERSYSTEMERROR_PFCINPUTRELAY 0x0080
#define BF_POWERSYSTEMERROR_OUTPUTRELAY 0x0100
#define BF_POWERSYSTEMERROR_BYPASSRELAY 0x0200
#define BF_POWERSYSTEMERROR_PFC 0x0800
#define BF_POWERSYSTEMERROR_DCBUSOVERVOLTAGE 0x1000
#define BF_POWERSYSTEMERROR_INVERTER 0x2000
#define BF_BATTERYSYSTEMERROR_DISCONNECTED 0x0001
#define BF_BATTERYSYSTEMERROR_OVERVOLTAGE 0x0002
#define BF_BATTERYSYSTEMERROR_NEEDSREPLACEMENT 0x0004
#define BF_BATTERYSYSTEMERROR_OVERTEMPERATURECRITICAL 0x0008
#define BF_BATTERYSYSTEMERROR_CHARGER 0x0010
#define BF_BATTERYSYSTEMERROR_TEMPERATURESENSOR 0x0020
#define BF_BATTERYSYSTEMERROR_BUSSOFTSTART 0x0040
#define BF_REPLACEBATTERYTESTSTATUS_PENDING 0x0001
#define BF_REPLACEBATTERYTESTSTATUS_INPROGRESS 0x0002
#define BF_REPLACEBATTERYTESTSTATUS_PASSED 0x0004
#define BF_REPLACEBATTERYTESTSTATUS_FAILED 0x0008
#define BF_REPLACEBATTERYTESTSTATUS_REFUSED 0x0010
#define BF_REPLACEBATTERYTESTSTATUS_ABORTED 0x0020
#define BF_REPLACEBATTERYTESTSTATUS_PROTOCOL 0x0040
#define BF_REPLACEBATTERYTESTSTATUS_LOCALUI 0x0080
#define BF_REPLACEBATTERYTESTSTATUS_INTERNAL 0x0100
#define BF_REPLACEBATTERYTESTSTATUS_INVALIDSTATE 0x0200
#define BF_REPLACEBATTERYTESTSTATUS_INTERNALFAULT 0x0400
#define BF_REPLACEBATTERYTESTSTATUS_STATEOFCHARGENOTACCEPTABLE 0x0800
#define BF_RUNTIMECALIBRATIONSTATUS_PENDING 0x0001
#define BF_RUNTIMECALIBRATIONSTATUS_INPROGRESS 0x0002
#define BF_RUNTIMECALIBRATIONSTATUS_PASSED 0x0004
#define BF_RUNTIMECALIBRATIONSTATUS_FAILED 0x0008
#define BF_RUNTIMECALIBRATIONSTATUS_REFUSED 0x0010
#define BF_RUNTIMECALIBRATIONSTATUS_ABORTED 0x0020
#define BF_RUNTIMECALIBRATIONSTATUS_PROTOCOL 0x0040
#define BF_RUNTIMECALIBRATIONSTATUS_LOCALUI 0x0080
#define BF_RUNTIMECALIBRATIONSTATUS_INTERNAL 0x0100
#define BF_RUNTIMECALIBRATIONSTATUS_INVALIDSTATE 0x0200
#define BF_RUNTIMECALIBRATIONSTATUS_INTERNALFAULT 0x0400
#define BF_RUNTIMECALIBRATIONSTATUS_STATEOFCHARGENOTACCEPTABLE 0x0800
#define BF_RUNTIMECALIBRATIONSTATUS_LOADCHANGE 0x1000
#define BF_RUNTIMECALIBRATIONSTATUS_ACINPUTNOTACCEPTABLE 0x2000
#define BF_RUNTIMECALIBRATIONSTATUS_LOADTOOLOW 0x4000
#define BF_RUNTIMECALIBRATIONSTATUS_OVERCHARGEINPROGRESS 0x8000
#define BF_LIFETIMESTATUS_LIFETIMESTATUSOK 0x0001
#define BF_LIFETIMESTATUS_LIFETIMENEAREND 0x0002
#define BF_LIFETIMESTATUS_LIFETIMEEXCEEDED 0x0004
#define BF_LIFETIMESTATUS_LIFETIMENEARENDACKNOWLEDGED 0x0008
#define BF_LIFETIMESTATUS_LIFETIMEEXCEEDEDACKNOWLEDGED 0x0010
#define BF_USERINTERFACESTATUS_CONTINUOUSTESTINPROGRESS 0x0001
#define BF_USERINTERFACESTATUS_AUDIBLEALARMINPROGRESS 0x0002
#define BF_USERINTERFACESTATUS_AUDIBLEALARMMUTED 0x0004
#define BF_INPUT_INPUTSTATUS_ACCEPTABLE 0x0001
#define BF_INPUT_INPUTSTATUS_PENDINGACCEPTABLE 0x0002
#define BF_INPUT_INPUTSTATUS_VOLTAGETOOLOW 0x0004
#define BF_INPUT_INPUTSTATUS_VOLTAGETOOHIGH 0x0008
#define BF_INPUT_INPUTSTATUS_DISTORTED 0x0010
#define BF_INPUT_INPUTSTATUS_BOOST 0x0020
#define BF_INPUT_INPUTSTATUS_TRIM 0x0040
#define BF_INPUT_INPUTSTATUS_FREQUENCYTOOLOW 0x0080
#define BF_INPUT_INPUTSTATUS_FREQUENCYTOOHIGH 0x0100
#define BF_INPUT_INPUTSTATUS_FREQANDPHASENOTLOCKED 0x0200
#define BF_VOLTAGEACSETTING_VAC120 0x0040
#define BF_UPSCOMMAND_RESTOREFACTORYSETTINGS 0x0008
#define BF_SIMPLESIGNALINGCOMMAND_REQUESTSHUTDOWN 0x0001
#define BF_SIMPLESIGNALINGCOMMAND_REMOTEOFF 0x0002
#define BF_SIMPLESIGNALINGCOMMAND_REMOTEON 0x0004
#define BF_UPSTESTSTATUS_START 0x0001
#define BF_RUNTIMECALIBRATIONCOMMAND_START 0x0001
#define BF_RUNTIMECALIBRATIONCOMMAND_ABORT 0x0002
#define BF_USERINTERFACECOMMAND_SHORTTEST 0x0001
#define BF_USERINTERFACECOMMAND_CONTINUOUSTEST 0x0002
#define BF_USERINTERFACECOMMAND_MUTEALLACTIVEAUDIBLEALARMS 0x0004
#define BF_USERINTERFACECOMMAND_CANCELMUTE 0x0008
#define BF_USERINTERFACECOMMAND_ACKNOWLEDGEBATTERYALARMS 0x0020
#define BF_OUTLETSTATUS_STATEON 0x0001
#define BF_OUTLETSTATUS_STATEOFF 0x0002
#define BF_OUTLETSTATUS_PROCESSREBOOT 0x0004
#define BF_OUTLETSTATUS_PROCESSSHUTDOWN 0x0008
#define BF_OUTLETSTATUS_PROCESSSLEEP 0x0010
#define BF_OUTLETSTATUS_PENDINGOFFDELAY 0x0080
#define BF_OUTLETSTATUS_PENDINGONACPRESENCE 0x0100
#define BF_OUTLETSTATUS_PENDINGONMINRUNTIME 0x0200
#define BF_OUTLETSTATUS_MEMBERGROUPPROCESS1 0x0400
#define BF_OUTLETSTATUS_MEMBERGROUPPROCESS2 0x0800
#define BF_OUTLETSTATUS_LOWRUNTIME 0x1000
#define BF_OUTLETCOMMAND_CANCEL 0x0001
#define BF_OUTLETCOMMAND_OUTPUTON 0x0002
#define BF_OUTLETCOMMAND_OUTPUTOFF 0x0004
#define BF_OUTLETCOMMAND_OUTPUTSHUTDOWN 0x0008
#define BF_OUTLETCOMMAND_OUTPUTREBOOT 0x0010
#define BF_OUTLETCOMMAND_COLDBOOTALLOWED 0x0020
#define BF_OUTLETCOMMAND_USEONDELAY 0x0040
#define BF_OUTLETCOMMAND_USEOFFDELAY 0x0080
#define BF_OUTLETCOMMAND_UNSWITCHEDOUTLETGROUP 0x0100
#define BF_OUTLETCOMMAND_SWITCHEDOUTLETGROUP0 0x0200
#define BF_OUTLETCOMMAND_SWITCHEDOUTLETGROUP1 0x0400
#define BF_OUTLETCOMMAND_SWITCHEDOUTLETGROUP2 0x0800
#define BF_OUTLETCOMMAND_USBPORT 0x1000
#define BF_OUTLETCOMMAND_LOCALUSER 0x2000
#define BF_OUTLETCOMMAND_RJ45PORT 0x4000
#define BF_OUTLETCOMMAND_SMARTSLOT1 0x8000
#define BF_I_SOGRELAYCONFIGSETTING_MOGPRESENT 0x0001
#define BF_I_SOGRELAYCONFIGSETTING_SOG0PRESENT 0x0002
#define BF_I_SOGRELAYCONFIGSETTING_SOG1PRESENT 0x0004
#define BF_I_SOGRELAYCONFIGSETTING_SOG2PRESENT 0x0008
#define BF_I_SOGRELAYCONFIGSETTING_SOG3PRESENT 0x0010

extern info_lkp_t start_auto_info[];

// Code is generated automatically upon 'Modbus Implementation in APC Smart-UPS' (http://www.apc.com/salestools/MPAO-98KJ7F/MPAO-98KJ7F_R1_EN.pdf)

extern info_lkp_t apc_smt_MB_upsstatus[];
extern info_lkp_t apc_smt_MB_simplesignalingstatus[];
extern info_lkp_t apc_smt_MB_generalerror[];
extern info_lkp_t apc_smt_MB_powersystemerror[];
extern info_lkp_t apc_smt_MB_batterysystemerror[];
extern info_lkp_t apc_smt_MB_replacebatteryteststatus[];
extern info_lkp_t apc_smt_MB_runtimecalibrationstatus[]; 
extern info_lkp_t apc_smt_MB_runtimecalibrationstatus_bw[];
extern info_lkp_t apc_smt_MB_lifetimestatus[];
extern info_lkp_t apc_smt_MB_userinterfacestatus[];
extern info_lkp_t apc_smt_MB_input_inputstatus[];
extern info_lkp_t apc_smt_MB_voltageacsetting[];
extern info_lkp_t apc_smt_MB_acceptablefrequencysetting[];
extern info_lkp_t apc_smt_MB_upscommand[];
extern info_lkp_t apc_smt_MB_simplesignalingcommand[];
extern info_lkp_t apc_smt_MB_upsteststatus[];
extern info_lkp_t apc_smt_MB_runtimecalibrationcommand[];
extern info_lkp_t apc_smt_MB_userinterfacecommand[];
extern info_lkp_t apc_smt_MB_outletstatus[];
extern info_lkp_t apc_smt_MB_outletstatus_bw[];
extern info_lkp_t apc_smt_MB_outletcommand[];
extern info_lkp_t apc_smt_MB_i_sogrelayconfigsetting[];

#endif /* APC_HID_H */
